from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 783)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 50, 121, 21))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(150, 50, 271, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_1.setGeometry(QtCore.QRect(450, 50, 311, 21))
        self.comboBox_1.setObjectName("comboBox")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(450, 30, 221, 16))
        self.label_9.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 30, 211, 21))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(780, 40, 421, 721))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 100, 121, 151))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 110, 271, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 90, 241, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 130, 221, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 150, 271, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 170, 221, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 190, 271, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 230, 271, 21))
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(450, 110, 271, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 210, 221, 16))
        self.label_5.setObjectName("label_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(450, 140, 221, 16))
        self.label_11.setObjectName("label_11")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 270, 411, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 300, 411, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 330, 411, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 370, 91, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 370, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 400, 91, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 400, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(250, 370, 171, 51))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 430, 91, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 460, 91, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 490, 91, 21))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 520, 91, 21))
        self.pushButton_12.setObjectName("pushButton_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(120, 430, 113, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(120, 460, 113, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(120, 490, 113, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(120, 520, 113, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(250, 430, 171, 51))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(250, 490, 171, 51))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 570, 91, 21))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 610, 91, 21))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 650, 91, 21))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(320, 560, 101, 111))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(450, 270, 311, 23))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(450, 300, 311, 23))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(450, 370, 311, 43))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(450, 690, 311, 71))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(120, 610, 181, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(120, 570, 181, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(120, 650, 181, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(120, 550, 191, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(120, 590, 191, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 630, 191, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(450, 90, 211, 16))
        self.label_10.setObjectName("label_8")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 690, 411, 71))
        self.pushButton_19.setObjectName("pushButton_19")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCalculate_OT = QtWidgets.QAction(MainWindow)
        self.actionCalculate_OT.setObjectName("actionCalculate_OT")
        self.actionMake_final_report = QtWidgets.QAction(MainWindow)
        self.actionMake_final_report.setObjectName("actionMake_final_report")
        self.actionCs_CCA = QtWidgets.QAction(MainWindow)
        self.actionCs_CCA.setObjectName("actionCs_CCA")
        self.actionMorning_workers = QtWidgets.QAction(MainWindow)
        self.actionMorning_workers.setObjectName("actionMorning_workers")
        self.actionHalf_day_workers = QtWidgets.QAction(MainWindow)
        self.actionHalf_day_workers.setObjectName("actionHalf_day_workers")
        self.actionSales_CCA = QtWidgets.QAction(MainWindow)
        self.actionSales_CCA.setObjectName("actionSales_CCA")
        self.actionCS_Name_CCA = QtWidgets.QAction(MainWindow)
        self.actionCS_Name_CCA.setObjectName("actionCS_Name_CCA")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Download"))
        self.label.setText(_translate("MainWindow", "Please choose month for downloading"))
        self.pushButton_2.setText(_translate("MainWindow", "Calculate OT"))
        self.label_2.setText(_translate("MainWindow", "Input luckers at first friday of the month"))
        self.label_3.setText(_translate("MainWindow", "Input luckers at second friday of the month"))
        self.label_4.setText(_translate("MainWindow", "Input luckers at third friday of the month"))
        self.label_5.setText(_translate("MainWindow", "Input luckers at fourth friday of the month"))
        self.label_10.setText(_translate("MainWindow", "Input luckers at fifth friday of the month"))
        self.label_11.setText(_translate("MainWindow", "Input luckers with comma, without spaces"))
        self.label_9.setText(_translate("MainWindow", "Please choose type of report for downloading"))
        self.pushButton_3.setText(_translate("MainWindow", "Make final OT report"))
        self.pushButton_4.setText(_translate("MainWindow", "Make attendance record file"))
        self.pushButton_5.setText(_translate("MainWindow", "Make backups"))
        self.pushButton_6.setText(_translate("MainWindow", "Add CS CCA"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete Cs CCA"))
        self.pushButton_8.setText(_translate("MainWindow", "Print Cs CCA"))
        self.pushButton_9.setText(_translate("MainWindow", "Add half day"))
        self.pushButton_10.setText(_translate("MainWindow", "Delete half day"))
        self.pushButton_11.setText(_translate("MainWindow", "Add sales CCA"))
        self.pushButton_12.setText(_translate("MainWindow", "Delete sales CCA"))
        self.pushButton_13.setText(_translate("MainWindow", "Print half day CCA"))
        self.pushButton_14.setText(_translate("MainWindow", "Print Sales CCA"))
        self.pushButton_15.setText(_translate("MainWindow", "Update CS name"))
        self.pushButton_16.setText(_translate("MainWindow", "Add CS name"))
        self.pushButton_17.setText(_translate("MainWindow", "Delete CS name"))
        self.pushButton_18.setText(_translate("MainWindow", "Print Cs dict"))
        self.pushButton_19.setText(_translate("MainWindow", "Save all workers lists"))
        self.pushButton_20.setText(_translate('MainWindow', "Prepare Daily files"))
        self.pushButton_21.setText(_translate('MainWindow', "Make Daily report"))
        self.pushButton_22.setText(_translate('MainWindow', "Prepare all Reports for new month"))
        self.pushButton_23.setText(_translate('MainWindow', "Terminate Excel processes"))
        self.label_6.setText(_translate("MainWindow", "New name, Old name. Without space"))
        self.label_7.setText(_translate("MainWindow", "Name, CCA id. Without space"))
        self.label_8.setText(_translate("MainWindow", " Name"))

        self.actionCalculate_OT.setText(_translate("MainWindow", "Calculate OT"))
        self.actionMake_final_report.setText(_translate("MainWindow", "Make final report"))
        self.actionCs_CCA.setText(_translate("MainWindow", "Cs CCA"))
        self.actionMorning_workers.setText(_translate("MainWindow", "Morning workers"))
        self.actionHalf_day_workers.setText(_translate("MainWindow", "Half day workers"))
        self.actionSales_CCA.setText(_translate("MainWindow", "Sales CCA"))
        self.actionCS_Name_CCA.setText(_translate("MainWindow", "CS Name + CCA"))
